version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    # Override labels to only `dependencies`
    labels: [dependencies]
    commit-message:
      prefix: '[dep] '
    # Only enable security updates (triggered by Dependabot alerts)
    open-pull-requests-limit: 0
    # Update both `package.json` and `yarn.lock`
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: '[chore] '
