name: Issue labeler
on:
  issues:
    types: [opened]
permissions:
  contents: read
jobs:
  label-component:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # To federate tokens
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/datadog-ci
          policy: self.issue-labeler
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@25f1485edffc1fee3ea68eb9f59a72e58720ffc4 # v3.2.2
        id: issue-parser
      - name: Set labels based on command
        uses: redhat-plumbers-in-action/advanced-issue-labeler@9e55064634b67244f7deb4211452b4a7217b93de # v3.0.0
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          token: ${{ steps.octo-sts.outputs.token }}
